export const cityActionTypes = {
    SET_CITIES_START: 'SET_CITIES_START',
    SET_CIITIES_SUCCESS: 'SET_CITIES_SUCCESS',
    SET_CITIES_FAILURE: 'SET_CITIES_FAILURE',
    SET_SEARCH_KEY: 'SET_SEARCH_KEY'
}